steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "build-api"
    args:
      - "build"
      - "--platform"
      - "linux/amd64"
      - "-t"
      - "us-central1-docker.pkg.dev/f1optimizer/f1-optimizer/api:latest"
      - "-f"
      - "docker/Dockerfile.api"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    id: "build-ml"
    args:
      - "build"
      - "--platform"
      - "linux/amd64"
      - "-t"
      - "us-central1-docker.pkg.dev/f1optimizer/f1-optimizer/ml:latest"
      - "-f"
      - "docker/Dockerfile.ml"
      - "."

  # ── Workbench deployment (opt-in: set _DEPLOY_WORKBENCH=true) ─────────────
  # Step 1: find an available zone and write it to infra/terraform/.workbench_zone
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "find-workbench-zone"
    entrypoint: bash
    args:
      - "-c"
      - |
        if [ "$_DEPLOY_WORKBENCH" = "true" ]; then
          bash scripts/find_workbench_zone.sh > infra/terraform/.workbench_zone
          echo "Workbench zone selected: $(cat infra/terraform/.workbench_zone)"
        else
          echo "Skipping zone selection — set _DEPLOY_WORKBENCH=true to deploy workbench"
        fi
    waitFor: ["build-api", "build-ml"]

  # Step 2: terraform init + apply targeting only the workbench instance
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "deploy-workbench"
    entrypoint: bash
    args:
      - "-c"
      - |
        if [ "$_DEPLOY_WORKBENCH" = "true" ]; then
          curl -fsSL https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip \
            -o /tmp/tf.zip
          unzip -q /tmp/tf.zip -d /usr/local/bin/
          terraform -chdir=infra/terraform init -input=false
          terraform -chdir=infra/terraform apply \
            -var-file=dev.tfvars \
            -target=null_resource.find_workbench_zone \
            -target=google_workbench_instance.f1_ml_workbench \
            -auto-approve -input=false
        else
          echo "Skipping workbench deploy — set _DEPLOY_WORKBENCH=true to enable"
        fi
    waitFor: ["find-workbench-zone"]

substitutions:
  _DEPLOY_WORKBENCH: "false"

images:
  - "us-central1-docker.pkg.dev/f1optimizer/f1-optimizer/api:latest"
  - "us-central1-docker.pkg.dev/f1optimizer/f1-optimizer/ml:latest"
