steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--platform"
      - "linux/amd64"
      - "-t"
      - "us-central1-docker.pkg.dev/f1optimizer/f1-optimizer/api:latest"
      - "-f"
      - "docker/Dockerfile.api"
      - "."

images:
  - "us-central1-docker.pkg.dev/f1optimizer/f1-optimizer/api:latest"
